# Generated by Django 5.2 on 2025-04-12 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_comment_blog_comment_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comment_blog',
        ),
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.blog'),
        ),
    ]
