# Generated by Django 5.2 on 2025-04-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_blog_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsubscription',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
