# Generated by Django 5.2 on 2025-04-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_emailsubscription_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='READ_ME',
            field=models.CharField(default='test', editable=False),
        ),
    ]
