# Generated by Django 5.2 on 2025-04-14 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_teachers_read_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='READ_ME',
        ),
    ]
