# Generated by Django 5.2 on 2025-04-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_teachers_update_font_awesome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='UPDATE_FONT_AWESOME',
            field=models.CharField(default='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css', max_length=200),
        ),
    ]
