# Generated by Django 5.2 on 2025-04-14 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_teachers_update_font_awesome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='UPDATE_FONT_AWESOME',
        ),
    ]
