# Generated by Django 5.2 on 2025-04-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_teachers_update_font_awesome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update_Font_Awesome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UPDATE_FONT_AWESOME', models.CharField(default='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css', max_length=200)),
            ],
        ),
    ]
