# Generated by Django 5.2 on 2025-04-14 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_update_font_awesome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update_font_awesome',
            old_name='UPDATE_FONT_AWESOME',
            new_name='update_url',
        ),
    ]
