# Generated by Django 5.2 on 2025-04-14 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_rename_update_font_awesome_update_font_awesome_update_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Update_Font_Awesome',
            new_name='UpdateFontAwesome',
        ),
    ]
