# Generated by Django 5.2 on 2025-04-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_updatefontawesome_update_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatefontawesome',
            name='READ_ME',
            field=models.TextField(default='Buradan saytdakı ikonların çağırıldıqı plugini sadəcə aşaqıdakı urli dəyişərək update edə bilərsən.Bəs necə update edək ? Mən sizə sacədə linkdəki rəqəmləri dəyişməyiməsləhət görərəmhttps://cdnjs.cloudflare.com/ajax/libs/font-awesome/<VERSIYA>/css/all.min.css', editable=False),
        ),
    ]
