# Generated by Django 5.2 on 2025-04-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_updatefontawesome_read_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='READ_ME',
            field=models.TextField(default='Burada Social Media iconlarının sadəcə adını yazaraq iconlarını çağırısan:', editable=False),
        ),
    ]
