# Generated by Django 5.2 on 2025-04-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_teachers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexslider',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='indexslider',
            name='url',
            field=models.CharField(),
        ),
    ]
