# Generated by Django 5.2 on 2025-04-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_indexslider_image_alter_indexslider_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='h1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
