# Generated by Django 5.2 on 2025-04-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_courses_h1_alter_courses_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_comment_count',
            field=models.CharField(max_length=10),
        ),
    ]
