# Generated by Django 5.2 on 2025-04-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_courses_course_comment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getintouch',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='getintouch',
            name='location_url',
            field=models.URLField(max_length=50),
        ),
        migrations.AlterField(
            model_name='getintouch',
            name='social_media_icon_1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='getintouch',
            name='social_media_icon_2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='getintouch',
            name='social_media_icon_3',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='getintouch',
            name='social_media_icon_4',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='getintouch',
            name='social_media_url_1',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='getintouch',
            name='social_media_url_2',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='getintouch',
            name='social_media_url_3',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='getintouch',
            name='social_media_url_4',
            field=models.URLField(max_length=100),
        ),
    ]
