# Generated by Django 5.2 on 2025-04-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_getintouch_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='url',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='exploretopsubjects',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
