# Generated by Django 5.2 on 2025-06-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_alter_courseregistration_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default_profile.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
